package com.cascer.mealreceipe.utils

import com.cascer.mealreceipe.data.local.entity.MealEntity
import com.cascer.mealreceipe.data.remote.response.CategoryResponse
import com.cascer.mealreceipe.data.remote.response.MealResponse
import com.cascer.mealreceipe.domain.model.Category
import com.cascer.mealreceipe.domain.model.Meal

object DataMapper {

    fun Meal.toEntity() = MealEntity(
        idMeal = idMeal,
        strMeal = strMeal,
        strMealThumb = strMealThumb
    )

    fun MealEntity.toDomain() = Meal(
        dateModified = "",
        idMeal = idMeal,
        strArea = "",
        strCategory = "",
        strCreativeCommonsConfirmed = "",
        strDrinkAlternate = "",
        strImageSource = "",
        strIngredient1 = "",
        strIngredient2 = "",
        strIngredient3 = "",
        strIngredient4 = "",
        strIngredient5 = "",
        strIngredient6 = "",
        strIngredient7 = "",
        strIngredient8 = "",
        strIngredient9 = "",
        strIngredient10 = "",
        strIngredient11 = "",
        strIngredient12 = "",
        strIngredient13 = "",
        strIngredient14 = "",
        strIngredient15 = "",
        strIngredient16 = "",
        strIngredient17 = "",
        strIngredient18 = "",
        strIngredient19 = "",
        strIngredient20 = "",
        strMealThumb = strMealThumb,
        strInstructions = "",
        strMeal = strMeal,
        strMeasure1 = "",
        strMeasure2 = "",
        strMeasure3 = "",
        strMeasure4 = "",
        strMeasure5 = "",
        strMeasure6 = "",
        strMeasure7 = "",
        strMeasure8 = "",
        strMeasure9 = "",
        strMeasure10 = "",
        strMeasure11 = "",
        strMeasure12 = "",
        strMeasure13 = "",
        strMeasure14 = "",
        strMeasure15 = "",
        strMeasure16 = "",
        strMeasure17 = "",
        strMeasure18 = "",
        strMeasure19 = "",
        strMeasure20 = "",
        strSource = "",
        strTags = "",
        strYoutube = "",
    )

    fun MealResponse.toDomain() = Meal(
        dateModified = dateModified.orEmpty(),
        idMeal = idMeal.orEmpty(),
        strArea = strArea.orEmpty(),
        strCategory = strCategory.orEmpty(),
        strCreativeCommonsConfirmed = strCreativeCommonsConfirmed.orEmpty(),
        strDrinkAlternate = strDrinkAlternate.orEmpty(),
        strImageSource = strImageSource.orEmpty(),
        strIngredient1 = strIngredient1.orEmpty(),
        strIngredient2 = strIngredient2.orEmpty(),
        strIngredient3 = strIngredient3.orEmpty(),
        strIngredient4 = strIngredient4.orEmpty(),
        strIngredient5 = strIngredient5.orEmpty(),
        strIngredient6 = strIngredient6.orEmpty(),
        strIngredient7 = strIngredient7.orEmpty(),
        strIngredient8 = strIngredient8.orEmpty(),
        strIngredient9 = strIngredient9.orEmpty(),
        strIngredient10 = strIngredient10.orEmpty(),
        strIngredient11 = strIngredient11.orEmpty(),
        strIngredient12 = strIngredient12.orEmpty(),
        strIngredient13 = strIngredient13.orEmpty(),
        strIngredient14 = strIngredient14.orEmpty(),
        strIngredient15 = strIngredient15.orEmpty(),
        strIngredient16 = strIngredient16.orEmpty(),
        strIngredient17 = strIngredient17.orEmpty(),
        strIngredient18 = strIngredient18.orEmpty(),
        strIngredient19 = strIngredient19.orEmpty(),
        strIngredient20 = strIngredient20.orEmpty(),
        strMealThumb = strMealThumb.orEmpty(),
        strInstructions = strInstructions.orEmpty(),
        strMeal = strMeal.orEmpty(),
        strMeasure1 = strMeasure1.orEmpty(),
        strMeasure2 = strMeasure2.orEmpty(),
        strMeasure3 = strMeasure3.orEmpty(),
        strMeasure4 = strMeasure4.orEmpty(),
        strMeasure5 = strMeasure5.orEmpty(),
        strMeasure6 = strMeasure6.orEmpty(),
        strMeasure7 = strMeasure7.orEmpty(),
        strMeasure8 = strMeasure8.orEmpty(),
        strMeasure9 = strMeasure9.orEmpty(),
        strMeasure10 = strMeasure10.orEmpty(),
        strMeasure11 = strMeasure11.orEmpty(),
        strMeasure12 = strMeasure12.orEmpty(),
        strMeasure13 = strMeasure13.orEmpty(),
        strMeasure14 = strMeasure14.orEmpty(),
        strMeasure15 = strMeasure15.orEmpty(),
        strMeasure16 = strMeasure16.orEmpty(),
        strMeasure17 = strMeasure17.orEmpty(),
        strMeasure18 = strMeasure18.orEmpty(),
        strMeasure19 = strMeasure19.orEmpty(),
        strMeasure20 = strMeasure20.orEmpty(),
        strSource = strSource.orEmpty(),
        strTags = strTags.orEmpty(),
        strYoutube = strYoutube.orEmpty(),
    )

    fun CategoryResponse.toDomain() = Category(
        idCategory = idCategory.orEmpty(),
        strCategory = strCategory.orEmpty(),
        strCategoryThumb = strCategoryThumb.orEmpty(),
        strCategoryDescription = strCategoryDescription.orEmpty()
    )

    fun emptyMeal() = Meal(
        dateModified = "",
        idMeal = "",
        strArea = "",
        strCategory = "",
        strCreativeCommonsConfirmed = "",
        strDrinkAlternate = "",
        strImageSource = "",
        strIngredient1 = "",
        strIngredient2 = "",
        strIngredient3 = "",
        strIngredient4 = "",
        strIngredient5 = "",
        strIngredient6 = "",
        strIngredient7 = "",
        strIngredient8 = "",
        strIngredient9 = "",
        strIngredient10 = "",
        strIngredient11 = "",
        strIngredient12 = "",
        strIngredient13 = "",
        strIngredient14 = "",
        strIngredient15 = "",
        strIngredient16 = "",
        strIngredient17 = "",
        strIngredient18 = "",
        strIngredient19 = "",
        strIngredient20 = "",
        strMealThumb = "",
        strInstructions = "",
        strMeal = "",
        strMeasure1 = "",
        strMeasure2 = "",
        strMeasure3 = "",
        strMeasure4 = "",
        strMeasure5 = "",
        strMeasure6 = "",
        strMeasure7 = "",
        strMeasure8 = "",
        strMeasure9 = "",
        strMeasure10 = "",
        strMeasure11 = "",
        strMeasure12 = "",
        strMeasure13 = "",
        strMeasure14 = "",
        strMeasure15 = "",
        strMeasure16 = "",
        strMeasure17 = "",
        strMeasure18 = "",
        strMeasure19 = "",
        strMeasure20 = "",
        strSource = "",
        strTags = "",
        strYoutube = "",
    )
}